# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/osx'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end


Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'NSPanel'
  app.xcode_dir = '/Applications/Xcode6-Beta.app/Contents/Developer'
end
