# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/osx'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end
require 'motion-kit'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'TrackMix'
end
